/**
 * Per-org runtime configuration. THIS FILE IS REGENERATED BY THE BACKEND
 * BUILD PIPELINE on every publish — `AstroSiteGeneratorService.generateProject`
 * overwrites the constants below with the org's real values before invoking
 * `bun run build`. The committed contents are placeholders so the template
 * compiles at template-author time.
 *
 * Spec: specs/004-astro-website-publishing/contracts/public-org-api.md
 *       "Embedding the keys + IDs at build time"
 */

// Public, read-only per-org API key (`pk_*`) — query-param auth for /api/v1/*.
export const PUBLIC_API_KEY = '__PUBLIC_API_KEY__';

// Base URL for the backend public API (no trailing slash).
export const PUBLIC_API_BASE_URL = '__PUBLIC_API_BASE_URL__';

// Organization persistent identifier.
export const ORG_ID = '__ORG_ID__';

// Organization slug used by /public/booking/*, /public/store/*, /public/cart/*
// and /public/checkout/* (the path-based endpoints used by the BookingFlow +
// Cart + Checkout islands).
export const ORG_SLUG = '__ORG_SLUG__';

// Locale used by the booking + cart i18n. Build-time constant per org.
export const LOCALE: 'es' | 'en' | 'pt' = 'es';

/**
 * Helper for the catalog shells. Always appends `?key=` against the v1 API.
 */
export function v1(path: string): string {
  const separator = path.includes('?') ? '&' : '?';
  return `${PUBLIC_API_BASE_URL}/api/v1${path}${separator}key=${PUBLIC_API_KEY}`;
}

/**
 * Helper for the public/* path-based endpoints (booking, store detail, cart,
 * checkout). These do NOT take the pk_* key — they resolve org by slug.
 */
export function publicPath(path: string): string {
  return `${PUBLIC_API_BASE_URL}/public${path}`;
}
